-- Piplio Backend – Initial word data
-- Import via: mysql -u USER -p DATABASE < InitialData.sql
-- Or paste into phpMyAdmin / TYPO3 Install Tool > SQL

-- ─── ARTIKEL EASY ─────────────────────────────────────────────────────────────
INSERT INTO tx_pipliobackend_word (pid, hidden, deleted, crdate, tstamp, topic, difficulty, word, artikel) VALUES
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Hund','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Apfel','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Ball','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Vogel','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Tisch','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Mond','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Käse','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Stuhl','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Arm','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Kopf','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Finger','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Fuß','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Zug','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Ring','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Katze','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Maus','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Blume','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Schule','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Sonne','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Nase','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Birne','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Zeit','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Stadt','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Nacht','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Farbe','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Uhr','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Zahl','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Welt','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Haus','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Kind','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Buch','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Auto','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Bett','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Boot','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Wort','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Licht','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Geld','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Feuer','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Gras','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','easy','Holz','das');

-- ─── ARTIKEL MEDIUM ───────────────────────────────────────────────────────────
INSERT INTO tx_pipliobackend_word (pid, hidden, deleted, crdate, tstamp, topic, difficulty, word, artikel) VALUES
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Baum','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Stern','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Schuh','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Kuchen','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Löwe','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Regen','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Schnee','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','König','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Berg','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Fluss','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Sand','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Topf','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Turm','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Ast','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Tür','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Hand','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Tasche','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Schnecke','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Giraffe','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Rakete','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Ente','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Wolke','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Wiese','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Stimme','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Tante','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Insel','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Welle','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Feder','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Pferd','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Tier','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Glas','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Huhn','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Eis','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Bild','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Schloss','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Nest','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Loch','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Meer','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Tal','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','medium','Ei','das');

-- ─── ARTIKEL HARD ─────────────────────────────────────────────────────────────
INSERT INTO tx_pipliobackend_word (pid, hidden, deleted, crdate, tstamp, topic, difficulty, word, artikel) VALUES
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Schmetterling','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Regenbogen','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Käfer','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Elefant','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Schrank','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Teppich','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Spiegel','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Hammer','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Kalender','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Pinsel','der'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Flugzeug','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Fenster','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Fahrrad','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Gesicht','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Abenteuer','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Geheimnis','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Kissen','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Messer','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Regal','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Dach','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Tor','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Werkzeug','das'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Gabel','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Treppe','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Straße','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Küche','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Brücke','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Zunge','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Schere','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Nadel','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Wand','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Decke','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Flasche','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Pflanze','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Socke','die'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_artikel','hard','Lampe','die');

-- ─── REIME EASY ───────────────────────────────────────────────────────────────
INSERT INTO tx_pipliobackend_word (pid, hidden, deleted, crdate, tstamp, topic, difficulty, word, rhyme_words, no_rhyme_words) VALUES
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_reime','easy','Maus','Haus,raus','Ball,Hund,Baum,Fisch'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_reime','easy','Ball','Fall,Hall,Stall','Maus,Hund,Baum,Fisch'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_reime','easy','Hund','Mund,Bund,rund','Ball,Maus,Stern,Baum'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_reime','easy','Tisch','Fisch,frisch','Haus,Baum,Ball,Hund'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_reime','easy','Baum','Traum,Raum,Schaum','Hund,Ball,Maus,Fisch'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_reime','easy','Schuh','Kuh,Ruh','Ball,Maus,Hund,Stern'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_reime','easy','Kind','Wind,Rind,blind','Ball,Maus,Hund,Buch'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_reime','easy','Bein','klein,Stein,fein','Ball,Maus,Hund,Baum'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_reime','easy','Ring','sing,bring,Ding','Ball,Maus,Hund,Baum'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_reime','easy','Hut','gut,Mut,Wut','Ball,Maus,Hund,Kind'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_reime','easy','Zoo','so,wo,froh','Ball,Hund,Baum,Fisch'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_reime','easy','Meer','mehr,leer,schwer','Ball,Maus,Hund,Kind'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_reime','easy','Schnee','See,Tee,Fee','Ball,Maus,Hund,Baum'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_reime','easy','Tor','vor,Rohr,Ohr','Ball,Maus,Hund,Baum'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_reime','easy','Zug','Krug,klug,Flug','Ball,Maus,Hund,Ring');

-- ─── REIME MEDIUM ─────────────────────────────────────────────────────────────
INSERT INTO tx_pipliobackend_word (pid, hidden, deleted, crdate, tstamp, topic, difficulty, word, rhyme_words, no_rhyme_words) VALUES
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_reime','medium','Stern','fern,Kern,gern','Ball,Maus,Baum,Hund'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_reime','medium','Buch','Tuch,Fluch,Besuch','Ball,Maus,Hund,Stern'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_reime','medium','Nacht','Macht,gedacht,Wacht','Ball,Maus,Hund,Stern'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_reime','medium','Tag','lag,mag,Schlag','Ball,Maus,Hund,Stern'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_reime','medium','Eis','heiß,weiß,Preis','Ball,Maus,Hund,Stern'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_reime','medium','Licht','nicht,dicht,Pflicht','Ball,Maus,Hund,Stern'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_reime','medium','Hase','Nase,Vase,Phase','Hund,Ball,Maus,Stern'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_reime','medium','Gabel','Kabel,Fabel','Hund,Ball,Maus,Stern'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_reime','medium','Blatt','glatt,satt,platt','Ball,Maus,Hund,Stern'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_reime','medium','Zeit','weit,breit,leid','Ball,Maus,Hund,Stern'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_reime','medium','Turm','Sturm,Wurm','Ball,Maus,Hund,Licht'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_reime','medium','Kopf','Zopf,Topf','Ball,Maus,Hund,Stern'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_reime','medium','Stein','Wein,fein,allein','Ball,Maus,Hund,Baum'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_reime','medium','Geld','Feld,Held,Welt','Ball,Maus,Hund,Stern'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_reime','medium','Zahl','Wahl,Tal,Mal','Ball,Maus,Hund,Stern');

-- ─── GROSS/KLEIN – NOMEN ──────────────────────────────────────────────────────
INSERT INTO tx_pipliobackend_word (pid, hidden, deleted, crdate, tstamp, topic, difficulty, word, is_nomen) VALUES
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','easy','Hund',1),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','easy','Katze',1),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','easy','Haus',1),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','easy','Schule',1),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','easy','Baum',1),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','easy','Kind',1),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','easy','Vogel',1),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','easy','Buch',1),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','easy','Ball',1),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','easy','Sonne',1),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','easy','Blume',1),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','easy','Tisch',1),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','easy','Stern',1),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','easy','Auto',1),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','easy','Stuhl',1);

-- GROSS/KLEIN – VERBEN
INSERT INTO tx_pipliobackend_word (pid, hidden, deleted, crdate, tstamp, topic, difficulty, word, is_nomen) VALUES
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','medium','laufen',0),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','medium','spielen',0),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','medium','schlafen',0),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','medium','trinken',0),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','medium','schreiben',0),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','medium','singen',0),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','medium','klettern',0),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','medium','tanzen',0),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','medium','malen',0),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','medium','schwimmen',0),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','medium','springen',0),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','medium','lesen',0),
-- GROSS/KLEIN – ADJEKTIVE
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','hard','groß',0),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','hard','klein',0),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','hard','schnell',0),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','hard','schön',0),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','hard','laut',0),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','hard','leise',0),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','hard','warm',0),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','hard','kalt',0),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','hard','hell',0),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','hard','dunkel',0),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','hard','süß',0),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_gross_klein','hard','sauer',0);

-- ─── WORTARTEN ────────────────────────────────────────────────────────────────
INSERT INTO tx_pipliobackend_word (pid, hidden, deleted, crdate, tstamp, topic, difficulty, word, word_type) VALUES
-- Easy Nomen
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','easy','Hund','Nomen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','easy','Katze','Nomen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','easy','Haus','Nomen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','easy','Ball','Nomen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','easy','Baum','Nomen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','easy','Sonne','Nomen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','easy','Mond','Nomen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','easy','Buch','Nomen'),
-- Easy Verb
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','easy','laufen','Verb'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','easy','springen','Verb'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','easy','schlafen','Verb'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','easy','singen','Verb'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','easy','malen','Verb'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','easy','hüpfen','Verb'),
-- Easy Adjektiv
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','easy','groß','Adjektiv'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','easy','klein','Adjektiv'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','easy','schnell','Adjektiv'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','easy','schön','Adjektiv'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','easy','warm','Adjektiv'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','easy','alt','Adjektiv'),
-- Medium Nomen
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','medium','Schule','Nomen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','medium','Tisch','Nomen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','medium','Auto','Nomen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','medium','Vogel','Nomen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','medium','Kind','Nomen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','medium','Blume','Nomen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','medium','Stern','Nomen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','medium','König','Nomen'),
-- Medium Verb
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','medium','trinken','Verb'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','medium','schreiben','Verb'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','medium','spielen','Verb'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','medium','lesen','Verb'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','medium','tanzen','Verb'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','medium','kochen','Verb'),
-- Medium Adjektiv
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','medium','leise','Adjektiv'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','medium','kalt','Adjektiv'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','medium','rot','Adjektiv'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','medium','rund','Adjektiv'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','medium','süß','Adjektiv'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','medium','hoch','Adjektiv'),
-- Hard Nomen
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','hard','Schmetterling','Nomen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','hard','Regenbogen','Nomen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','hard','Elefant','Nomen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','hard','Abenteuer','Nomen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','hard','Geheimnis','Nomen'),
-- Hard Verb
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','hard','beobachten','Verb'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','hard','flüstern','Verb'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','hard','entdecken','Verb'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','hard','erklären','Verb'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','hard','verwandeln','Verb'),
-- Hard Adjektiv
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','hard','neugierig','Adjektiv'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','hard','fröhlich','Adjektiv'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','hard','tapfer','Adjektiv'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','hard','mutig','Adjektiv'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_wortarten','hard','aufgeregt','Adjektiv');

-- ─── PLURAL ───────────────────────────────────────────────────────────────────
INSERT INTO tx_pipliobackend_word (pid, hidden, deleted, crdate, tstamp, topic, difficulty, word, plural_form, wrong_options) VALUES
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','easy','Hund','Hunde','Hunds,Hünde,Hunden'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','easy','Katze','Katzen','Katzs,Kätze,Katzens'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','easy','Auto','Autos','Autoes,Autoen,Äutos'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','easy','Schuh','Schuhe','Schuhs,Schühe,Schuhen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','easy','Bett','Betten','Betts,Bette,Bötten'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','easy','Tisch','Tische','Tischs,Tischen,Tischem'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','easy','Stern','Sterne','Sterns,Sternen,Sternet'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','easy','Blume','Blumen','Blumes,Blümen,Blumens'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','easy','Arm','Arme','Arms,Ärme,Armen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','easy','Tag','Tage','Tags,Täge,Tagen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','easy','Ring','Ringe','Rings,Ränge,Ringen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','easy','Schaf','Schafe','Schafs,Schäfe,Schafen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','easy','Affe','Affen','Affes,Äffe,Affens'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','easy','Uhr','Uhren','Uhrs,Ühr,Uhrens'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','easy','Brief','Briefe','Briefs,Bräfe,Briefen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','easy','Zelt','Zelte','Zelts,Zälte,Zelten'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','easy','Heft','Hefte','Hefts,Häfte,Heften'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','easy','Pilz','Pilze','Pilzs,Pilzen,Pälze'),
-- Medium
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','medium','Haus','Häuser','Hauser,Häuse,Hauses'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','medium','Kind','Kinder','Kinds,Kindes,Kindere'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','medium','Baum','Bäume','Baums,Baume,Bäumen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','medium','Buch','Bücher','Buchs,Buche,Büchen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','medium','Hand','Hände','Hands,Handen,Händes'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','medium','Ball','Bälle','Balls,Balle,Bälles'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','medium','Vogel','Vögel','Vogels,Vogele,Vögels'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','medium','Zug','Züge','Zugs,Zuge,Zügen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','medium','Wald','Wälder','Walds,Walde,Wäldere'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','medium','Fluss','Flüsse','Flusses,Flüssen,Flussee'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','medium','Topf','Töpfe','Topfs,Topfe,Töpfen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','medium','Ast','Äste','Asts,Aste,Ästen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','medium','Hut','Hüte','Huts,Hüten,Hütes'),
-- Hard
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','hard','Apfel','Äpfel','Apfels,Apfele,Äpfels'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','hard','Maus','Mäuse','Mause,Mausen,Mäusen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','hard','Stuhl','Stühle','Stuhls,Stuhle,Stühlen'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','hard','Glas','Gläser','Glasen,Gläse,Gläsers'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','hard','Zahn','Zähne','Zahns,Zahne,Zähnse'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','hard','Bruder','Brüder','Bruders,Brüdern,Brudern'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','hard','Nagel','Nägel','Nagels,Nagele,Nägeln'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','hard','Garten','Gärten','Gartens,Gartene,Gärtens'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','hard','Mantel','Mäntel','Mantels,Mantele,Mänteln'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','hard','Hammer','Hämmer','Hammers,Hammere,Hämmern'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','hard','Vater','Väter','Vaters,Vatere,Vätern'),
(1,0,0,UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'deutsch_plural','hard','Laden','Läden','Ladens,Ladene,Lädens');
